# NLP: Part 0- Introduction, Handling Text Data

In [40]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

## Tokenize

In [41]:
# Create sample sentences
sentences = ['I love my dog', 'I love my cat', 'You love my dog!', 'Do you think my dog is amazing?']

In [42]:
# Create tokenizer
# num_words: By setting this hyperparameter, tokenizer take the top 100 words by volume
# With oov_token the unseen data can handle as over vocabulary words
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
print('\nWord Index = ',word_index)

# Create sequences
sequences = tokenizer.texts_to_sequences(sentences)
print('\nSequences = ',sequences)


Word Index =  {'<OOV>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}

Sequences =  [[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]


## Padding

In [51]:
padded = pad_sequences(sequences)
print('Padded Sequences:\n\n',padded)

Padded Sequences:

 [[ 0  0  0  5  3  2  4]
 [ 0  0  0  5  3  2  7]
 [ 0  0  0  6  3  2  4]
 [ 8  6  9  2  4 10 11]]


In [50]:
# Create customized padding
# padding = post add zeros after sequences. 
# maxlen = 5 add limitation on words to 5. so, any extra words remove from begining the sentences.
# truncating = post remove extra words from ending the sentences.
padded_c = pad_sequences(sequences, padding='post', truncating='post', maxlen=5)
print('Customized Padded Sequences:\n\n',padded_c)

Customized Padded Sequences:

 [[5 3 2 4 0]
 [5 3 2 7 0]
 [6 3 2 4 0]
 [8 6 9 2 4]]


In [49]:
# Try with words that the tokenizer wasn't fit to
test_data = ['i really love my dog', 'my dog loves my manatee']
test_seq = tokenizer.texts_to_sequences(test_data)
print('\nTest Sequences = ',test_seq)
padded = pad_sequences(test_seq, maxlen=10)
print('\nPadded Test Sequences:\n\n', padded)


Test Sequences =  [[5, 1, 3, 2, 4], [2, 4, 1, 2, 1]]

Padded Test Sequences:

 [[0 0 0 0 0 5 1 3 2 4]
 [0 0 0 0 0 2 4 1 2 1]]
